version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html                                     # Links our src directory to the /var/www directory in the container - any changes we make to our local files will be reflected in the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf     # Links our nginx.conf file to the default.conf file in the container
    depends_on:                                                 # These need to be started before the nginx container
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: ['composer']
    networks:
      - laravel
  
  npm:
    image: node:21
    container_name: npm
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel